/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/group/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRequest"];
                    "text/json": components["schemas"]["CreateRequest"];
                    "application/*+json": components["schemas"]["CreateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateResponse"];
                        "application/json": components["schemas"]["CreateResponse"];
                        "text/json": components["schemas"]["CreateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        Content?: string;
                        GroupUuid?: string;
                        Photos?: components["schemas"]["IFormFile"][];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostResponse"];
                        "application/json": components["schemas"]["PostResponse"];
                        "text/json": components["schemas"]["PostResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    GroupUuid?: string;
                    CursorDateTime?: string;
                    CursorPostUuid?: string;
                    Limit?: number;
                };
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FeedResponse"];
                        "application/json": components["schemas"]["FeedResponse"];
                        "text/json": components["schemas"]["FeedResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/feed/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    GroupUuid?: string;
                    CursorDateTime?: string;
                    CursorPostUuid?: string;
                    Limit?: number;
                };
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FeedResponse"];
                        "application/json": components["schemas"]["FeedResponse"];
                        "text/json": components["schemas"]["FeedResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/delete-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeletePostRequest"];
                    "text/json": components["schemas"]["DeletePostRequest"];
                    "application/*+json": components["schemas"]["DeletePostRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/group/update-post": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GoogleLoginRequest"];
                    "text/json": components["schemas"]["GoogleLoginRequest"];
                    "application/*+json": components["schemas"]["GoogleLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GoogleLoginResponse"];
                        "application/json": components["schemas"]["GoogleLoginResponse"];
                        "text/json": components["schemas"]["GoogleLoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/post/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PutLikeRequest"];
                    "text/json": components["schemas"]["PutLikeRequest"];
                    "application/*+json": components["schemas"]["PutLikeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LikeResponse"];
                        "application/json": components["schemas"]["LikeResponse"];
                        "text/json": components["schemas"]["LikeResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DeleteLikeRequest"];
                    "text/json": components["schemas"]["DeleteLikeRequest"];
                    "application/*+json": components["schemas"]["DeleteLikeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LikeResponse"];
                        "application/json": components["schemas"]["LikeResponse"];
                        "text/json": components["schemas"]["LikeResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/post/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PostUuid?: string;
                };
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Comment"][];
                        "application/json": components["schemas"]["Comment"][];
                        "text/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PutCommentRequest"];
                    "text/json": components["schemas"]["PutCommentRequest"];
                    "application/*+json": components["schemas"]["PutCommentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Comment"][];
                        "application/json": components["schemas"]["Comment"][];
                        "text/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DeleteCommentRequest"];
                    "text/json": components["schemas"]["DeleteCommentRequest"];
                    "application/*+json": components["schemas"]["DeleteCommentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Comment"][];
                        "application/json": components["schemas"]["Comment"][];
                        "text/json": components["schemas"]["Comment"][];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: {
                    "X-Google-Sub"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["GetGroupsResponse"];
                        "application/json": components["schemas"]["GetGroupsResponse"];
                        "text/json": components["schemas"]["GetGroupsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/avatar/{userUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userUuid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Comment: {
            /** Format: uuid */
            commentUuid: string;
            /** Format: uuid */
            postUuid: string;
            /** Format: uuid */
            userUuid: string;
            content: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            deletedAt: string | null;
        };
        CreateRequest: {
            groupName: string;
        };
        CreateResponse: {
            createdGroup: components["schemas"]["Group"];
        };
        DeleteCommentRequest: {
            /** Format: uuid */
            postUuid: string;
            /** Format: uuid */
            commentUuid: string;
        } | null;
        DeleteLikeRequest: {
            /** Format: uuid */
            postUuid: string;
            /** Format: uuid */
            mutationUuid: string;
        } | null;
        DeletePostRequest: {
            postUuid: string;
        };
        FeedCursor: {
            /** Format: date-time */
            dateTime: string;
            /** Format: uuid */
            postUuid: string;
        } | null;
        FeedItem: {
            post: components["schemas"]["Post"];
            photos: components["schemas"]["Photo"][] | null;
            likedByMe: boolean;
            /** Format: int32 */
            likeCount: number;
        };
        FeedResponse: {
            feedPosts: components["schemas"]["FeedItem"][];
            hasMore: boolean;
            nextCursor: components["schemas"]["FeedCursor"];
        };
        GetGroupsResponse: {
            groups: components["schemas"]["Group"][];
        };
        GoogleLoginRequest: {
            googleIdToken: string | null;
        };
        GoogleLoginResponse: {
            userUuid: string;
            isNewUser: boolean;
        };
        Group: {
            /** Format: uuid */
            groupUuid: string;
            name?: string | null;
            pic?: string | null;
        };
        /** Format: binary */
        IFormFile: string;
        LikeResponse: {
            isSuccess: boolean;
            isLikedByMe: boolean;
            /** Format: int32 */
            likeCount: number;
            /** Format: uuid */
            mutationUuid: string;
        };
        Photo: {
            /** Format: uuid */
            photoUuid?: string;
            /** Format: uuid */
            postUuid?: string;
            /** Format: int32 */
            sortOrder: number;
            /** Format: uuid */
            worldUuid: string | null;
            /** Format: int32 */
            width: number;
            /** Format: int32 */
            height: number;
            /** Format: int64 */
            size: number;
            /** Format: byte */
            hash?: string | null;
            format: string | null;
        };
        Post: {
            /** Format: uuid */
            postUuid: string;
            /** Format: uuid */
            groupUuid: string;
            /** Format: uuid */
            userUuid: string;
            content: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        PostResponse: {
            /** Format: uuid */
            groupUuid: string;
            /** Format: uuid */
            postUuid: string;
        };
        PutCommentRequest: {
            /** Format: uuid */
            postUuid: string;
            content: string;
        } | null;
        PutLikeRequest: {
            /** Format: uuid */
            postUuid: string;
            /** Format: uuid */
            mutationUuid: string;
        } | null;
        UserDto: {
            /** Format: uuid */
            userUuid: string;
            nickname: string;
            pic: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
