import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const appleSdGothicNeo = localFont({
  variable: "--font-apple-sans",
  display: "swap",
  src: [
    { path: "../public/fonts/AppleSDGothicNeoUL.ttf", weight: "100", style: "normal" },
    { path: "../public/fonts/AppleSDGothicNeoT.ttf", weight: "200", style: "normal" },
    { path: "../public/fonts/AppleSDGothicNeoL.ttf", weight: "300", style: "normal" },
    { path: "../public/fonts/AppleSDGothicNeoR.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/AppleSDGothicNeoM.ttf", weight: "500", style: "normal" },
    { path: "../public/fonts/AppleSDGothicNeoSB.ttf", weight: "600", style: "normal" },
    { path: "../public/fonts/AppleSDGothicNeoB.ttf", weight: "700", style: "normal" },
    { path: "../public/fonts/AppleSDGothicNeoEB.ttf", weight: "800", style: "normal" },
    { path: "../public/fonts/AppleSDGothicNeoH.ttf", weight: "900", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${appleSdGothicNeo.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
            {children}
      </body>
    </html>
  );
}
