// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116020056_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Server.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("GroupUuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupUuid", "UserUuid");

                    b.HasIndex("UserUuid")
                        .HasDatabaseName("IX_Member_UserUuid_Active")
                        .HasFilter("deletedAt IS NULL");

                    b.HasIndex("GroupUuid", "JoinedAt")
                        .HasDatabaseName("IX_Member_GroupUuid_JoinedAt_Active")
                        .HasFilter("deletedAt IS NULL");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupUuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PlaceUuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewSrc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Src")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SrcHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uuid");

                    b.HasIndex("PlaceUuid");

                    b.HasIndex("SrcHash")
                        .HasDatabaseName("IX_Photo_SrcHash");

                    b.HasIndex("GroupUuid", "SrcHash")
                        .IsUnique()
                        .HasDatabaseName("UX_Photo_GroupUuid_SrcHash");

                    b.HasIndex("PostUuid", "SortOrder")
                        .HasDatabaseName("IX_Photo_PostUuid_SortOrder");

                    b.HasIndex("GroupUuid", "CreatedAt", "SortOrder")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Photo_GroupUuid_CreatedAt_DESC_SortOrder_DESC");

                    b.ToTable("Photo", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Place", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("ValidatedVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uuid");

                    b.ToTable("Place", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("UserUuid");

                    b.HasIndex("GroupUuid", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Post_GroupUuid_CreatedAt_DESC");

                    b.HasIndex("GroupUuid", "UserUuid", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Post_GroupUser_CreatedAt_DESC_Active")
                        .HasFilter("deletedAt IS NULL");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.PostComment", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PostUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Uuid");

                    b.HasIndex("UserUuid");

                    b.HasIndex("PostUuid", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PostComment_PostUuid_CreatedAt_DESC_Active")
                        .HasFilter("deletedAt IS NULL");

                    b.ToTable("PostComment", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.PostTag", b =>
                {
                    b.Property<Guid>("PostUuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetUserUuid")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PostUuid", "TargetUserUuid");

                    b.HasIndex("TargetUserUuid");

                    b.HasIndex("PostUuid", "CreatedAt")
                        .HasDatabaseName("IX_PostTag_PostUuid_CreatedAt");

                    b.ToTable("PostTag", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Uuid");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Server.Domain.Entities.Member", b =>
                {
                    b.HasOne("Server.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Domain.Entities.Photo", b =>
                {
                    b.HasOne("Server.Domain.Entities.Group", "Group")
                        .WithMany("Photos")
                        .HasForeignKey("GroupUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Domain.Entities.Place", "Place")
                        .WithMany("Photos")
                        .HasForeignKey("PlaceUuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Server.Domain.Entities.Post", "Post")
                        .WithMany("Photos")
                        .HasForeignKey("PostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Place");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Server.Domain.Entities.Post", b =>
                {
                    b.HasOne("Server.Domain.Entities.Group", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Domain.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Domain.Entities.PostComment", b =>
                {
                    b.HasOne("Server.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Domain.Entities.PostTag", b =>
                {
                    b.HasOne("Server.Domain.Entities.Post", "Post")
                        .WithMany("Tags")
                        .HasForeignKey("PostUuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Domain.Entities.User", "TargetUser")
                        .WithMany("PostTagsTargetingMe")
                        .HasForeignKey("TargetUserUuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Server.Domain.Entities.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Photos");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Server.Domain.Entities.Place", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Server.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Photos");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Server.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Memberships");

                    b.Navigation("PostTagsTargetingMe");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
